apiVersion: v1
kind: Pod
metadata:
  name: health-server-1
#  annotations:
#    k8s.v1.cni.cncf.io/networks: server-bridge
spec:
  nodeName: worker1
  volumes:

  - name: health
    persistentVolumeClaim:
      claimName: task-pv-claim

  - name: scaleout-monitor
    configMap:
       name: scaleout-monitor
       defaultMode: 0755
  - name: config-add
    configMap:
       name: config-add
       defaultMode: 0755

  - name: config-del
    configMap:
       name: config-del
       defaultMode: 0755
       items:
       - key: config_del.py
         path: config_del.py
  - name: config-init
    configMap:
       name: config-init
       defaultMode: 0755
       items:
       - key: config_init.py
         path: config_init.py

  containers:
  - name: health-server-1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: severalnines/centos-ssh
    securityContext:
      privileged: true
      runAsUser: 0

    volumeMounts:
      - mountPath: /tmp/health
        name: health
